---
- name: Destroy Deployment
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get list of VMs in the folder
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        folder: "{{ vm_folder }}"
      delegate_to: localhost
      register: vm_info

    - name: Destroy VMs
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        name: "{{ item.vm }}"
        state: absent
        force: true
      delegate_to: localhost
      loop: "{{ vm_info.virtual_machines }}"
      when: item.vm is match("(webserver|database|loadbalancer|monitoring)-vm-")

    - name: Remove VMs from AWX inventory
      ansible.builtin.uri:
        url: "{{ awx_url }}/api/v2/inventories/{{ awx_inventory_id }}/hosts/"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_token }}"
        status_code: 200
      register: awx_hosts
      delegate_to: localhost

    - name: Delete hosts from AWX inventory
      ansible.builtin.uri:
        url: "{{ awx_url }}/api/v2/hosts/{{ item.id }}/"
        method: DELETE
        headers:
          Authorization: "Bearer {{ awx_token }}"
        status_code: 204
      loop: "{{ awx_hosts.json.results }}"
      when: item.name is match("(webserver|database|loadbalancer|monitoring)-vm-")
      delegate_to: localhost

    - name: Display destruction summary
      ansible.builtin.debug:
        msg: 
          - "Deployment destruction complete."
          - "Destroyed VMs:"
          - "{{ vm_info.virtual_machines | map(attribute='vm') | select('match', '(webserver|database|loadbalancer|monitoring)-vm-') | list }}"
